apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod-argo-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/thieryl/my-argo.git
    targetRevision: HEAD
    path: production
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

