apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-stag-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/thieryl/my-argo.git
    targetRevision: HEAD
    path: staging
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-stag

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: false
      prune: true